{'categories': [3, 5, 66, 202, 203, 208, 213, 282],
 'category_ids': [3, 5, 66, 202, 203, 208, 213, 282],
 'color': 16,
 'color_': 288,
 'colorid_number': None,
 'country_of_manufacture': None,
 'created_at': 2014-10-24 23:04:56,
 'custom_design': None,
 'custom_design_from': None,
 'custom_design_to': None,
 'custom_layout_update': None,
 'description': <p>The coveted Laurel Satchel is structured, sleek, and chic.</p>
<p>Leather: Italian Cowhide<br />Length: 13in/33cm | Height: 9in/23cm | Depth: 3.5in/9cm</p>
,
 'enable_googlecheckout': 1,
 'gift_message_available': None,
 'gift_wrapping_available': None,
 'gift_wrapping_price': None,
 'google_category': Apparel & Accessories,
 'group_price': [],
 'has_options': 0,
 'image_label': Laurel Satchel in Sand,
 'is_recurring': 0,
 'is_returnable': 2,
 'meta_description': None,
 'meta_keyword': None,
 'meta_title': Laurel Satchel in Sand | Linea Pelle,
 'minimal_price': None,
 'msrp': None,
 'msrp_display_actual_price_type': 4,
 'msrp_enabled': 2,
 'name': Laurel Satchel,
 'news_from_date': None,
 'news_to_date': None,
 'old_id': None,
 'options_container': container2,
 'page_layout': None,
 'part_num': None,
 'price': 395.0000,
 'product_care': Linea Pelle products are made of Italian cowhide leathers. Animal skin is inherently prone to occasional blemishes or bruising, making each item truly unique. Please note, this tends to show more with light to medium colors. Reference our Customer Service section for more details on caring for your new Linea Pelle product.,
 'product_id': 9757,
 'recurring_profile': None,
 'related_tgtr_position_behavior': None,
 'related_tgtr_position_limit': None,
 'required_options': 0,
 'set': 10,
 'short_description': <li>Made of Italian cowhide leather, which is custom dyed exclusive Linea Pelle colors.</li>
<li>Shiny gold hardware on Black and Sand.</li> 
<li>Shiny silver hardware on Blush, Black Dots, and Dove.</li> 
<li>Includes special Linea Pelle pouch for storage and protection.</li>
,
 'sku': ZCH013S1519SND,
 'small_image_label': Laurel Satchel in Sand,
 'special_from_date': None,
 'special_price': None,
 'special_to_date': None,
 'status': 1,
 'tax_class_id': 2,
 'thumbnail_label': Laurel Satchel in Sand,
 'tier_price': [],
 'type': simple,
 'type_id': simple,
 'upc_code': 7052 0252 5404,
 'updated_at': 2014-10-30 17:13:00,
 'upsell_tgtr_position_behavior': None,
 'upsell_tgtr_position_limit': None,
 'url_key': laurel-satchel-f14-sand,
 'url_path': laurel-satchel-f14-sand,
 'visibility': 4,
 'websites': 1,
 'weight': None}
